// Code generated by protoc-gen-go.
// source: riemann_proto/riemann_proto.proto
// DO NOT EDIT!

/*
Package riemann_proto is a generated protocol buffer package.

It is generated from these files:
	riemann_proto/riemann_proto.proto

It has these top-level messages:
	State
	Event
	Query
	Msg
	Attribute
*/
package riemann_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Deprecated; state was used by early versions of the protocol, but not any
// more.
type State struct {
	Time             *int64   `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	State            *string  `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	Service          *string  `protobuf:"bytes,3,opt,name=service" json:"service,omitempty"`
	Host             *string  `protobuf:"bytes,4,opt,name=host" json:"host,omitempty"`
	Description      *string  `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Once             *bool    `protobuf:"varint,6,opt,name=once" json:"once,omitempty"`
	Tags             []string `protobuf:"bytes,7,rep,name=tags" json:"tags,omitempty"`
	Ttl              *float32 `protobuf:"fixed32,8,opt,name=ttl" json:"ttl,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *State) Reset()                    { *m = State{} }
func (m *State) String() string            { return proto.CompactTextString(m) }
func (*State) ProtoMessage()               {}
func (*State) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *State) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *State) GetState() string {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ""
}

func (m *State) GetService() string {
	if m != nil && m.Service != nil {
		return *m.Service
	}
	return ""
}

func (m *State) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *State) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *State) GetOnce() bool {
	if m != nil && m.Once != nil {
		return *m.Once
	}
	return false
}

func (m *State) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *State) GetTtl() float32 {
	if m != nil && m.Ttl != nil {
		return *m.Ttl
	}
	return 0
}

type Event struct {
	Time             *int64       `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	State            *string      `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	Service          *string      `protobuf:"bytes,3,opt,name=service" json:"service,omitempty"`
	Host             *string      `protobuf:"bytes,4,opt,name=host" json:"host,omitempty"`
	Description      *string      `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Tags             []string     `protobuf:"bytes,7,rep,name=tags" json:"tags,omitempty"`
	Ttl              *float32     `protobuf:"fixed32,8,opt,name=ttl" json:"ttl,omitempty"`
	Attributes       []*Attribute `protobuf:"bytes,9,rep,name=attributes" json:"attributes,omitempty"`
	MetricSint64     *int64       `protobuf:"zigzag64,13,opt,name=metric_sint64" json:"metric_sint64,omitempty"`
	MetricD          *float64     `protobuf:"fixed64,14,opt,name=metric_d" json:"metric_d,omitempty"`
	MetricF          *float32     `protobuf:"fixed32,15,opt,name=metric_f" json:"metric_f,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Event) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *Event) GetState() string {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ""
}

func (m *Event) GetService() string {
	if m != nil && m.Service != nil {
		return *m.Service
	}
	return ""
}

func (m *Event) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *Event) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *Event) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Event) GetTtl() float32 {
	if m != nil && m.Ttl != nil {
		return *m.Ttl
	}
	return 0
}

func (m *Event) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Event) GetMetricSint64() int64 {
	if m != nil && m.MetricSint64 != nil {
		return *m.MetricSint64
	}
	return 0
}

func (m *Event) GetMetricD() float64 {
	if m != nil && m.MetricD != nil {
		return *m.MetricD
	}
	return 0
}

func (m *Event) GetMetricF() float32 {
	if m != nil && m.MetricF != nil {
		return *m.MetricF
	}
	return 0
}

type Query struct {
	String_          *string `protobuf:"bytes,1,opt,name=string" json:"string,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Query) Reset()                    { *m = Query{} }
func (m *Query) String() string            { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()               {}
func (*Query) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Query) GetString_() string {
	if m != nil && m.String_ != nil {
		return *m.String_
	}
	return ""
}

type Msg struct {
	Ok               *bool    `protobuf:"varint,2,opt,name=ok" json:"ok,omitempty"`
	Error            *string  `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	States           []*State `protobuf:"bytes,4,rep,name=states" json:"states,omitempty"`
	Query            *Query   `protobuf:"bytes,5,opt,name=query" json:"query,omitempty"`
	Events           []*Event `protobuf:"bytes,6,rep,name=events" json:"events,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Msg) Reset()                    { *m = Msg{} }
func (m *Msg) String() string            { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()               {}
func (*Msg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Msg) GetOk() bool {
	if m != nil && m.Ok != nil {
		return *m.Ok
	}
	return false
}

func (m *Msg) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *Msg) GetStates() []*State {
	if m != nil {
		return m.States
	}
	return nil
}

func (m *Msg) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *Msg) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type Attribute struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            *string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Attribute) Reset()                    { *m = Attribute{} }
func (m *Attribute) String() string            { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()               {}
func (*Attribute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Attribute) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Attribute) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*State)(nil), "State")
	proto.RegisterType((*Event)(nil), "Event")
	proto.RegisterType((*Query)(nil), "Query")
	proto.RegisterType((*Msg)(nil), "Msg")
	proto.RegisterType((*Attribute)(nil), "Attribute")
}

func init() { proto.RegisterFile("riemann_proto/riemann_proto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x92, 0xcd, 0x4e, 0xe3, 0x30,
	0x10, 0x80, 0xe5, 0xfc, 0x35, 0x99, 0xf4, 0x67, 0xd7, 0xab, 0x76, 0xad, 0x3d, 0xac, 0x4c, 0x2e,
	0xf8, 0x14, 0x24, 0x84, 0xb8, 0x53, 0x89, 0x23, 0x12, 0x88, 0x07, 0xa8, 0x42, 0x6a, 0x52, 0xab,
	0x4d, 0x5c, 0xec, 0x69, 0xa5, 0x1e, 0x79, 0x41, 0x9e, 0x09, 0xd9, 0x4d, 0x05, 0x1c, 0x38, 0x72,
	0x89, 0x34, 0x9f, 0x26, 0x33, 0xf3, 0x8d, 0x07, 0xce, 0x8c, 0x92, 0x6d, 0xd5, 0x75, 0x8b, 0xad,
	0xd1, 0xa8, 0x2f, 0xbe, 0x44, 0xa5, 0xff, 0x16, 0xaf, 0x04, 0xe2, 0x47, 0xac, 0x50, 0xd2, 0x21,
	0x44, 0xa8, 0x5a, 0xc9, 0x08, 0x27, 0x22, 0xa4, 0x23, 0x88, 0xad, 0xc3, 0x2c, 0xe0, 0x44, 0x64,
	0x74, 0x02, 0x03, 0x2b, 0xcd, 0x5e, 0xd5, 0x92, 0x85, 0x1e, 0x0c, 0x21, 0x5a, 0x69, 0x8b, 0x2c,
	0xf2, 0xd1, 0x1f, 0xc8, 0x97, 0xd2, 0xd6, 0x46, 0x6d, 0x51, 0xe9, 0x8e, 0xc5, 0xa7, 0x14, 0xdd,
	0xd5, 0x92, 0x25, 0x9c, 0x88, 0xd4, 0x97, 0xaf, 0x1a, 0xcb, 0x06, 0x3c, 0x14, 0x19, 0xcd, 0x21,
	0x44, 0xdc, 0xb0, 0x94, 0x13, 0x11, 0x14, 0x6f, 0x04, 0xe2, 0xdb, 0xbd, 0xec, 0xf0, 0x47, 0x66,
	0xf8, 0xa6, 0x2b, 0xfd, 0x0f, 0x50, 0x21, 0x1a, 0xf5, 0xb4, 0x43, 0x69, 0x59, 0xc6, 0x43, 0x91,
	0x5f, 0x42, 0x79, 0x73, 0x42, 0x74, 0x0a, 0xa3, 0x56, 0xa2, 0x51, 0xf5, 0xc2, 0xaa, 0x0e, 0xaf,
	0xaf, 0xd8, 0x88, 0x13, 0x41, 0xe9, 0x2f, 0x48, 0x7b, 0xbc, 0x64, 0x63, 0x4e, 0x04, 0xf9, 0x44,
	0x9e, 0xd9, 0xc4, 0x0b, 0xfd, 0x85, 0xf8, 0x61, 0x27, 0xcd, 0x81, 0x8e, 0x21, 0xb1, 0x68, 0x54,
	0xd7, 0x78, 0xa3, 0xac, 0x68, 0x20, 0xbc, 0xb3, 0x0d, 0x05, 0x08, 0xf4, 0xda, 0x5b, 0xa5, 0x4e,
	0x52, 0x1a, 0xa3, 0x4d, 0xef, 0x34, 0x73, 0x7f, 0x54, 0x6e, 0xa2, 0xc8, 0x4f, 0x94, 0x94, 0xc7,
	0xd7, 0x99, 0x42, 0xfc, 0xe2, 0x4a, 0x7a, 0x2f, 0x87, 0x8f, 0x0d, 0x66, 0x90, 0x48, 0xb7, 0x39,
	0xcb, 0x92, 0x3e, 0xdd, 0x2f, 0xb2, 0x38, 0x87, 0xec, 0xc3, 0x24, 0x87, 0x70, 0x2d, 0x0f, 0x8c,
	0xf0, 0x40, 0x64, 0xae, 0xdf, 0xbe, 0xda, 0xec, 0xfa, 0xa5, 0xce, 0xff, 0xc1, 0xef, 0x5a, 0xb7,
	0x65, 0xb5, 0x5d, 0x1d, 0x4c, 0xd9, 0x1f, 0xc8, 0x3c, 0xbe, 0x77, 0xb7, 0xf1, 0x1e, 0x00, 0x00,
	0xff, 0xff, 0xcd, 0xc3, 0xfe, 0x15, 0x3f, 0x02, 0x00, 0x00,
}
